apiVersion: v1
kind: Service
metadata:
  name: bridge-web
spec:
  selector:
    app: bridge
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 40000
  type: loadBalancer
