apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: evanabonsignori@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-acme-prod
    solvers:
    - http01:
        ingress:
          class:  nginx

