apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-api
spec:
  selector:
    matchLabels:
      app: bridge
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: bridge
        tier: backend
        track: stable
    spec:
      containers:
        - name: bridge-api
          image: ebonsignori/bridge-api
          ports:
            - containerPort: 3000

